config/routes.rb
Projectstatus::Application.routes.draw do

  root 'projects#index'

  resources :projects do
    resources :cards
  end

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :project
  validates :title, presence: true,
            length: { minimum: 5 }
  validates :jenkins_url, presence: true
  validate :jenkins_url_is_valid

  def jenkins_url_is_valid
    unless %w( http https ).include?(URI.parse(jenkins_url).scheme)
      errors.add(:jenkins_url, 'is not a uri')
    end
  rescue URI::BadURIError
    errors.add(:jenkins_url, 'is a bad uri')
  rescue URI::InvalidURIError
    errors.add(:jenkins_url, 'is an invalid uri')
  end

  def build_report
    totalBuilds = self.num_builds
    failedBuilds = self.num_failed_builds
    passrate = ((totalBuilds - failedBuilds) / totalBuilds.to_f) * 100
    "#{passrate.round(2)}% #{failedBuilds} failed out of #{totalBuilds} total #{'build'.pluralize(totalBuilds)}"
  end

  def test_count_report
    if self.test_count == self.prev_test_count
      direction = 'no'
      difference = 'change'
    else
      if self.test_count > self.prev_test_count
        direction = 'up'
        difference = self.test_count - self.prev_test_count
      else
        direction = 'down'
        difference = self.prev_test_count - self.test_count
      end
    end
    "#{self.test_count} #{'test'.pluralize(self.test_count)} #{direction} #{difference} since last week"
  end

  def update_info
    now = Time.now

    if self.updated_time + Rails.application.config.update_interval > now
      logger.debug("need to wait #{Rails.application.config.update_interval} seconds")
      return
    end

    #now get updated values
    self.updated_time = now

    job_data = JenkinsJobData.new(jenkins_url,now)

    self.test_count = job_data.stats[:first_build_test_count]
    self.prev_test_count = job_data.stats[:last_build_test_count]
    self.num_builds = job_data.stats[:number_of_builds]
    self.num_failed_builds = job_data.stats[:number_of_failed_builds]

    self.save
  end
end

app/models/concerns/jenkins_job_data.rb
class JenkinsJobData
  attr_accessor :url
  attr_accessor :auth_details
  attr_accessor :participant_constraint_list
  attr_accessor :stats
  attr_accessor :update_start_time

  def initialize(jenkins_url, update_time)
    @url = "#{jenkins_url}/api/json?tree=builds[number,timestamp,id,result,actions[totalCount],changeSet[items[author[fullName]]]]"

    #Load config that might be related to this jenkins job
    @auth_details = NIL
    @participant_constraint_list = NIL
    Rails.application.config.jenkins_auth_map.each do | key,value |
      if jenkins_url =~ /#{key}/
        @auth_details = value
      end
    end
    Rails.application.config.jenkins_participant_map.each do | key,value |
      if jenkins_url =~ /#{key}/
        @participant_constraint_list = value
      end
    end

    @stats = {:number_of_builds => 0, :number_of_failed_builds => 0, :first_build_test_count => 0, :last_build_test_count => 0}
    @update_start_time = update_time
    load_data
  end

  private
  def load_data
    if auth_details.nil?
      response = HTTParty.get(@url)
    else
      response = HTTParty.get(@url, :basic_auth =>{:username => auth_details[:user], :password => auth_details[:pw]})
    end
    builds = response['builds']
    builds = [] if response['builds'].nil?
    builds.each do | build |
      buildTime = Time.at(build['timestamp'].to_f / 1000)
      if buildTime > @update_start_time - Rails.application.config.build_window
        this_build_counts = true
        unless @participant_constraint_list.nil?
          #only count the build if one of our team members was a participant
          build_participants = []
          build['changeSet']['items'].each { |item| build_participants << item['author']['fullName'] }
          this_build_counts = false
          unless build_participants.size == 0
            if @participant_constraint_list[:users].any? {|user| build_participants.include? user}
              this_build_counts = true
              Rails.logger.debug("we participated in this build #{@url} #{build['number']}")
            end
          end
        end
        if this_build_counts
          @stats[:number_of_builds] += 1
          unless build['result'] =~ /SUCCESS/
            @stats[:number_of_failed_builds] += 1
          end
          build_actions = build['actions']
          build_actions = [] if build['actions'].nil?
          build_actions.each do | actions |
            unless actions['totalCount'].nil?
              @stats[:first_build_test_count] = actions['totalCount'].to_i unless @stats[:first_build_test_count] > 0
              @stats[:last_build_test_count] = actions['totalCount'].to_i
            end
          end
        end
      end
    end

  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  has_many :cards, dependent: :destroy
  validates :title, presence: true,
            length: { minimum: 5 }

  friendly_id :title, use: :slugged

  attr_accessor :test_message, :build_message

  def generate_messages
    total_builds = 0
    total_failed_builds = 0
    total_tests = 0
    total_prev_tests = 0
    self.cards.each do | card |
      total_builds += card.num_builds
      total_failed_builds += card.num_failed_builds
      total_tests += card.test_count
      total_prev_tests += card.prev_test_count
    end
    passrate = ((total_builds - total_failed_builds) / total_builds.to_f) * 100
    if total_tests == total_prev_tests
      direction = 'no'
      difference = 'change'
    else
      if total_tests > total_prev_tests
        direction = 'up'
        difference = total_tests - total_prev_tests
      else
        direction = 'down'
        difference = total_prev_tests - total_tests
      end
    end
    self.test_message = "#{title} builds green #{passrate.round(2)}% of the time, #{total_failed_builds} failed out of #{total_builds} total #{'build'.pluralize(total_builds)}"
    self.build_message = "#{title} Tests executed with each checkin #{direction} #{difference} to #{total_tests}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
    @project = Project.friendly.find(params[:project_id])
    @card = Card.new
  end

  def create
    @project = Project.friendly.find(params[:project_id])
    @card = @project.cards.create(params[:card].permit(:title, :jenkins_url))
    if @card.save
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def destroy
    @project = Project.friendly.find(params[:project_id])
    @card = @project.cards.find(params[:id])
    @card.destroy
    redirect_to project_path(@project)
  end

  def show
    @project = Project.friendly.find(params[:project_id])
    @card = @project.cards.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project].permit(:title))
    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def edit
    @project = Project.friendly.find(params[:id])
  end

  def update
    @project = Project.friendly.find(params[:id])

    if @project.update(params[:project].permit(:title))
      redirect_to @project
    else
      render 'edit'
    end
  end

  def show
    @project = Project.friendly.find(params[:id])
    @card = Card.new
  end

  def index
    @projects = Project.all
  end

  def destroy
    @project = Project.friendly.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/cards/_card.html.erb
<% card.update_info %>

<div id="shell">
    <div id="title">
        <%= card.title %><div id="delete"><%= link_to 'X', [card.project, card],method: :delete, data: { confirm: 'Are you sure?' } %></div>
    </div>
    <div id="content"><%= card.test_count_report %><br/><%= card.build_report %><br/><a href="<%= card.jenkins_url %>">Jenkins Job</a><br/>Last Updated: <%= card.updated_time %></div>
</div>
<br/>

app/views/cards/_form.html.erb
<h2>Add a card:</h2>
<%= form_for([@project, @card]) do |f| %>
    <% if @card.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@card.errors.count, "error") %> prohibited
                this card from being saved:</h2>
            <ul>
                <% @card.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
        <%= f.label :title %><br />
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :jenkins_url %><br />
        <%= f.text_field :jenkins_url %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/cards/new.html.erb
<h1>New Card</h1>
<%= render 'form' %>
<%= link_to 'Back', project_path(@project) %>

app/views/cards/show.html.erb
<%= render @card %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projectstatus</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
    <% if @project.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@project.errors.count, "error") %> prohibited
                this project from being saved:</h2>
            <ul>
                <% @project.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>
<%= render 'form' %>
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
    <tr>
        <th>Title</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>

    <% @projects.each do |project| %>
        <tr>
            <td><%= project.title %></td>
            <td><%= link_to 'Show', project %></td>
            <td><%= link_to 'Edit', edit_project_path(project) %></td>
            <td><%= link_to 'Destroy', project_path(project),
                            method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
</table>
<%= link_to 'New project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form' %>
<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @project.title %>
</p>
<h2>Cards</h2>
<%= render @project.cards %>

<% @project.generate_messages %>

<%= @project.test_message %>
<br/>
<%= @project.build_message %>

<%= render 'cards/form' %>
<%= link_to 'Back', projects_path %>
| <%= link_to 'Edit', edit_project_path(@project) %>